/*

 * Copyright (c) 2001 Hewlett-Packard GmbH, Germany.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of
 * Hewlett-Packard, GmbH. ("Confidential Information").  You shall not
 * disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into
 * with Hewlett-Packard.
 *
 */

package com.hp.es.constants;

/**
 * Definition of constants for use in the ES.
 * @since ES 4.0
 */
public interface EsConstants {
    // --------------------------------------------------------
    // Common constants
    // --------------------------------------------------------
	String ES_MAJOR_VERSION = "10";
	String ES_MINOR_VERSION = "1";
	String ES_VERSION = "ES" + ES_MAJOR_VERSION + "_" + ES_MINOR_VERSION;
	String ES_TM_VERSION = "ES"+ ES_MAJOR_VERSION  + ES_MINOR_VERSION;

    /** BUILD NAME PROVIDED BY SOFTCM VIA SYMBOL NAME THAT IS USED FOR CHECKOUT */
    String RELEASE_STRING = "$Name: dev $";

    /** BUILD NAME WITHOUT LEADING "$Name: dev $" */
    String RELEASE_NAME =
        "@(#) HPSE release <" + RELEASE_STRING.substring(6, RELEASE_STRING.length()-1) + ">";

    /** ES SERVICE PROPERTIES FILE */
    String companyId = (System.getProperty("egitsbs.company")).toString().toLowerCase();
    //String ES_PROPERTIES_FILENAME = ES_VERSION + "/config/EntitlementService.properties";
    String ES_PROPERTIES_FILENAME = ES_VERSION + "/config/"+companyId+".EntitlementService.properties";

    /** The Mapp file name */
    String CODEMAPPING_PROPERTIES_FILENAME = ES_VERSION + "/config/ServiceCodeMapping.properties";
    /** The name of the properties file that holds overall settings and
     *  the operation manager config
     */
    String COMMON_PROPERTIES_FILENAME = ES_VERSION + "/config/CommonService.properties";

    /** ES SERVICE PROPERTIES FILE */
    String DB_PROPERTIES_FILENAME = ES_VERSION + "/config/db.properties";

    /** ES DB PROPERTIES FILE FOR LOCAL TESTING   */
    String DB_PROPERTIES_FILENAME_LOCAL = "src/main/resources/db.properties";

    /**
     * Interval in secs between 2 refreshes of dynamic config files.
     */
    long PROPS_RELOAD_SECS = 60;

    /** Country code prefic */
    String COUNTRY_CODE_MAPPING_PREFIX = "es.common.CountryCodeMapping.";

    String ES_PARALLEL_SOURCE_REQUEST_TIMEOUT = "es.warrantyservice.parallel.timeout";

    String SSL_PROTOCOL = "SSL";
    String UTF8_ENCODING = "UTF-8";
    String HTTP_HEADER = "Content-Type: text/xml; charset=UTF-8\r\n";

	String ES_SERVICE_ID = "es";
	String ES_DEFAULT_USER = "es";
	String ES_DEFAULT_PWD = "es";    

    /** End of line */
    String ENDOFLINE = "\n";

    /** Tabulation */
    String TAB = "\t";

    /** Prologue containing xml version tag as generated by CASTOR */
    String CASTOR_PROLOGUE = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\r";

    
    //---------------------------------------------------------
    // Contract Service Constants
    //---------------------------------------------------------
    String DB_SIMPLE_DATE_FORMAT= "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
    // --------------------------------------------------------
    // Warranty Service constants
    // --------------------------------------------------------
    String WARRANTY_SERVICE_PREFIX = "es.warrantyservice.";

	String WARRANTY_DETERMINATION_CODE_TABLE_PROPERTIES_FILENAME = ES_VERSION + "/config/WarrantyDeterminationCodeTable.properties";
    String WARRANTY_DETERMINATION_CODE_PRIORITY_PROPERTIES_FILENAME = ES_VERSION + "/config/WarrantyDeterminationCodePriority.properties";

    String WARRANTY_DETERMINATION_CODE_TABLE_FOR_ASTRO2_PROPERTIES_FILENAME = ES_VERSION + "/config/WarrantyDeterminationCodeTableForAstro2.properties";
    
	String SAP_FUNCTION_NAME_SWOP = "Z_WARRANTY_LOOKUP_PARALLEL_BSU";
	String SWOP_SOAP_PACKAGE_NAME = "com.hp.es.service.warrantyEntitlement.adapters.castorgenerated.Z_WARRANTY_LOOKUP_PARALLEL_BSU";
	String SWOP_SOAP_START_TAG    = "<ZWTYLOOKUP>";
	String SWOP_SOAP_END_TAG      = "</ZWTYLOOKUP>";
	String SWOP_SOAP_CLASSNAME    = "com.hp.es.service.warrantyEntitlement.adapters.castorgenerated.Z_WARRANTY_LOOKUP_PARALLEL_BSU.ZWTYLOOKUP";

    // --------------------------------------------------------
    // ASTRO2 CATS Service constants
    // --------------------------------------------------------
	String SAP_FUNCTION_NAME_ASTRO2 = "ZA2_FMAES_GETENT_V3_WS";
	String ASTRO2_SOAP_PACKAGE_NAME = "com.hp.es.service.catsAgreement.adapters.castorgenerated.ZA2_FMAES_GETENT_V3_WS";
//	String ASTRO2_SOAP_START_TAG    = "<ZA2_FMAES_GETENT_V3_WS>";
	String ASTRO2_SOAP_START_TAG    = "<rfc:ZA2_FMAES_GETENT_V3_WS.Response xmlns:rfc=\"urn:sap-com:document:sap:rfc:functions\">";
//	String ASTRO2_SOAP_END_TAG      = "</ZA2_FMAES_GETENT_V3_WS>";
	String ASTRO2_SOAP_END_TAG      = "</rfc:ZA2_FMAES_GETENT_V3_WS.Response>";
	
	String ASTRO2_SOAP_CLASSNAME    = "com.hp.es.service.catsAgreement.adapters.castorgenerated.ZA2_FMAES_GETENT_V3_WS.ZA2_FMAES_GETENT_V3_WS_Response";
	
	
	String START_DATE = "startdate";
	String END_DATE = "enddate";

    String SWOP_SWOPDISABLED_FLAG = "es.warrantyservice.swop.SwopDisabled";

    /** Country of service mapping file */
    String COUNTRY_OF_SERVICE_MAPPING_FILE = ES_VERSION + "/config/CountryOfServiceMapping.properties";
    
    String AMERICASCOUNTRIES_PROPERTIES_FILENAME = ES_VERSION + "/config/AmericasCountries.properties";
    String AMS_COUNTRIES="AMS_COUNTRY";
    
    String SWOP_STATUS_SUCCESSFULL = "Successful";
    String SWOP_STATUS_SYSTEM_NOT_AVAILABLE = "SystemNotAvailable";
    String SWOP_STATUS_NO_ENTRY_FOUND = "NoEntryFound";
    String SWOP_STATUS_ERROR = "Error";
    
    
	String SAP_FUNCTION_NAME_IBSEARCH = "Z_WARRANTY_WILDCARD_SEARCH";
	String IBSEARCH_SOAP_PACKAGE_NAME = "com.hp.es.service.ibSearch.adapters.castorgenerated.Z_WARRANTY_WILDCARD_SEARCH";
	String IBSEARCH_SOAP_START_TAG    = "<ZPRODUCTLIST>";
	String IBSEARCH_SOAP_END_TAG      = "</ZPRODUCTLIST>";
	String IBSEARCH_SOAP_CLASSNAME    = "com.hp.es.service.ibSearch.adapters.castorgenerated.Z_WARRANTY_WILDCARD_SEARCH.ZWTYWILDCARD";

	String SAP_FUNCTION_NAME_UNITEVENTHISTORY = "Z_WARRANTY_EVENT_HISTORY";
	String UNITEVENTHISTORY_SOAP_PACKAGE_NAME = "com.hp.es.service.unitEventHistory.adapters.castorgenerated.Z_WARRANTY_EVENT_HISTORY";
	String UNITEVENTHISTORY_SOAP_START_TAG    = "<Z_WARRANTY_EVENT_HISTORY>";
	String UNITEVENTHISTORY_SOAP_END_TAG      = "</Z_WARRANTY_EVENT_HISTORY>";
	String UNITEVENTHISTORY_SOAP_CLASSNAME    = "com.hp.es.service.unitEventHistory.adapters.castorgenerated.Z_WARRANTY_EVENT_HISTORY.Z_WARRANTY_EVENT_HISTORY";
	
	String FUNCTION_NAME_SNR_MFG = "ManufacturingInstalledBase";
	String SNR_MFG_SOAP_PACKAGE_NAME = "com.hp.es.service.manufacturingHeaderInformation.adapters.metrogenerated.ManufacturingInstalledBaseService";
	String SNR_MFG_SOAP_START_TAG    = "<ManufacturingInstalledBase>";
	String SNR_MFG_SOAP_END_TAG      = "</ManufacturingInstalledBase>";
	String SNR_MFG_SOAP_CLASSNAME    = "com.hp.es.service.manufacturingHeaderInformation.adapters.metrogenerated.ManufacturingInstalledBaseService.ManufacturingInstalledBaseService";
	
	
    // --------------------------------------------------------
    // Logging constants
    // --------------------------------------------------------
    String ES_LOG4J_PROPERTIES = ES_VERSION + "/config/es.log4j.properties";
    
    //String ITO_LOGGER_NAME="es" + ES_MAJOR_VERSION + ES_MINOR_VERSION + ".ito";
    String FILE_LOGGER_NAME="es" + ES_MAJOR_VERSION + ES_MINOR_VERSION + ".log";
    String STATISTICS_LOGGER_NAME="es" + ES_MAJOR_VERSION + ES_MINOR_VERSION + "_statistics.log";
	

	// Boolean values in ABAP
	String ABAP_TRUE = "X";
	String ABAP_FALSE = " ";
	
    // --------------------------------------------------------
    // CQS constants
    // --------------------------------------------------------	
	String SAP_FUNCTION_NAME_CQS_CONTRACT_ENT = "ZES_CONTRACT_ENT_ES10";
	String CQS_SOAP_PACKAGE_NAME = "com.hp.es.service.contractEntitlement.adapters.castorgenerated.CQS_FUNCTIONS";
	String CQS_SOAP_START_TAG    = "<rfc:ZES_CONTRACT_ENT_ES10.Response";
	String CQS_SOAP_END_TAG      = "</rfc:ZES_CONTRACT_ENT_ES10.Response>";
	String CQS_SOAP_CLASSNAME    = "com.hp.es.service.contractEntitlement.adapters.castorgenerated.CQS_FUNCTIONS.ZES_CONTRACT_ENT_ES10_Response";

    //CQS contractSummary
	String SAP_FUNCTION_NAME_CQS_CONTRACT_SUM = "ZES_CONTRACT_SUM_ES10";
	String CQSCS_SOAP_PACKAGE_NAME = "com.hp.es.service.contractSummary.adapters.castorgenerated.ZES_CONTRACT_SUM_ES10";
	String CQSCS_SOAP_START_TAG    = "<rfc:ZES_CONTRACT_SUM_ES10.Response";
	String CQSCS_SOAP_END_TAG      = "</rfc:ZES_CONTRACT_SUM_ES10.Response>";
	String CQSCS_SOAP_CLASSNAME    = "com.hp.es.service.contractSummary.adapters.castorgenerated.ZES_CONTRACT_SUM_ES10.ZES_CONTRACT_SUM_ES10_Response";
		
	String SAP_FUNCTION_NAME_CQS_CONTRACT_ENT_BYSN = "ZES_CONTRACT_ENT_BY_SN_ES10";
	String CQSBYSN_SOAP_PACKAGE_NAME = "com.hp.es.service.contractEntitlement.adapters.castorgenerated.CQS_FUNCTIONS";
	String CQSBYSN_SOAP_START_TAG    = "<rfc:ZES_CONTRACT_ENT_BY_SN_ES10.Response";
	String CQSBYSN_SOAP_END_TAG      = "</rfc:ZES_CONTRACT_ENT_BY_SN_ES10.Response>";
	String CQSBYSN_SOAP_CLASSNAME    = "com.hp.es.service.contractEntitlement.adapters.castorgenerated.CQS_FUNCTIONS.ZES_CONTRACT_ENT_BY_SN_ES10_Response";

    String SAP_FUNCTION_NAME_CQS_ROUTINGDETAILS = "ZES_ROUTING_DETAILS_ES10";
    String CQS_ROUTINGDETAILS_SOAP_PACKAGE_NAME = "com.hp.es.service.routingDetails.adapters.castorgenerated.ZES_ROUTING_DETAILS_ES10";
    String CQS_ROUTINGDETAILS_SOAP_START_TAG    = "<rfc:ZES_ROUTING_DETAILS_ES10.Response";
    String CQS_ROUTINGDETAILS_SOAP_END_TAG      = "</rfc:ZES_ROUTING_DETAILS_ES10.Response>";
    String CQS_ROUTINGDETAILS_SOAP_CLASSNAME    = "com.hp.es.service.routingDetails.adapters.castorgenerated.ZES_ROUTING_DETAILS_ES10.ZES_ROUTING_DETAILS_ES10_Response";
    
    
	String CQS_SYSTEM_NAME  = "SAP CQS ";
	String ODS_SYSTEM_NAME  = "ODS";
	String ODSCI_SYSTEM_NAME  = "ODS Customer Indicator";	
	String SWOP_SYSTEM_NAME = "SWOP";
	String ASTRO2_SYSTEM_NAME  = "ASTRO2";
	String WORKING_NAME_SWOP_SHIPMENT_DATE = "SWOP Shipment Date";
	
	
	String CQS_EMPTY_PROCESS_STATE   = "";
	String CQS_SUCCESS_PROCESS_STATE = "S";
	String CQS_WARNING_PROCESS_STATE = "W";
	String CQS_ERROR_PROCESS_STATE   = "E";
	
	
    String SOAP_HEADER =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" "
            + " xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
            + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"> \n"
            + "<soapenv:Body>\n";

    /** Standard SOAP footer */
    String SOAP_FOOTER = "</soapenv:Body>\n" + "</soapenv:Envelope>\n";
	
    
    //Plumbing page
    String ES_PLUMBING_SAP_SN="es.plumbing.sap.SN";
    String ES_PLUMBING_SAP_PN="es.plumbing.sap.PN";
    String ES_PLUMBING_SAP_COUNTRYCODE="es.plumbing.sap.countryCode";
    
    String ES_PLUMBING_SERVICE_SN="es.plumbing.service.SN";
    String ES_PLUMBING_SERVICE_COUNTRYCODE="es.plumbing.service.countryCode";
    
    String ES_PLUMBING_ASTRO2_SN="es.plumbing.ASTRO2.SN";
    String ES_PLUMBING_ASTRO2_PN="es.plumbing.ASTRO2.PN";
    String ES_PLUMBING_ASTRO2_COUNTRYCODE="es.plumbing.ASTRO2.countryCode";

    //ASTRO2
    String ES_WARRANTYINFO_SUPPORTLINE_CALLASTRO2 = "es.WarrantyInfo.SupportLine.callAstro2";
    String ASTRO2_PROP_PREFIX = "es.sap.ASTRO2";
    String ASTRO2_CALL_OPTION = ASTRO2_PROP_PREFIX + ".callOption";
    String ASTRO2_CLIENT_TYPE = ASTRO2_PROP_PREFIX + ".clientType";
    String ASTRO2_MAIN_URL = ASTRO2_PROP_PREFIX + ".mainUrl";
    
    //ES Operation 
    String GET_WAR_ENT = "GetWarrantyEntitlement";
    String GET_CON_ENT = "GetContractEntitlement";
    String GET_ENT_BY_SN = "GetEntitlementBySn";
    String GET_ENT_BY_PN = "GetEntitlementByPn";
    String GET_CON_SUM = "GetContractSummary";
    String GET_ROUTING_DETAILS = "GetRoutingDetails";
    String GET_IB_UNITS = "GetInstalledBaseUnits";
    String HTTP_OK = "HTTP/1.0 200";
    
    //ES Transaction Monitor switch
    String ES_TM_ENABLED = "es.tm.enabled";
    String ES_TM_INTERVAL = "es.tm.interval";
    String ES_JMS_PROVIDER = "es.jms.provider";
    
    //Fraud release
    String ES_FRAUD_ENABLED="es.fraud.enabled";
    
    //SOAP log message
    String ES_SOAP_LOGMESSAGE="es.soap.logMessage";
    
    //WebLogic Multi Data Source
    String DATASOURCE_READONLY_JNDINAME = "datasource.readonly.jndiName";
    String DATASOURCE_WRITABLE_JNDINAME = "datasource.writable.jndiName";
    String WEBLOGIC_DATASOURCE_ENABLE="weblogic.datasource.enable";
    
    //Invalid SN
    String ES_INVALID_SN="es.invalid.sn";
    String ES_INVALID_SN_PREFIX="es.invalid.sn.prefix";
    String ES_INVALID_SN_SUFFIX="es.invalid.sn.suffix";
    String ES_SN_MAXLENGTH = "es.sn.maxLength";
    String ES_SN_MINLENGTH = "es.sn.minLength";
    String ES_SN_WARRANTY_LEFT_TRIM_ENABLE="es.sn.warranty.left.trim.enable";
    
    // Added in MV project to check SN
    String ES_SN_CONTRACT_LEFT_TRIM_ENABLE = "es.sn.contract.left.trim.enable";
    String ES_SN_MAX_LEFT_TRIM_LENGTH = "es.sn.max.left.trim.length";
    
  //Invalid PN
    String ES_PN_MAXLENGTH = "es.pn.maxLength";
   // String ES_PN_MINLENGTH = "es.pn.minLength";
    
    // Added SNR constants
    String SNR_PROP_PREFIX="es.snr";
    String SNR_ENABLE="es.snr.enable";
    
    String ES_PLUMBING_SNR_SN = "es.plumbing.SNR.SN";
    String ES_PLUMBING_SNR_PN = "es.plumbing.SNR.PN";
    String SNR_SUCCESS = "E-0000";
    String SNR_USER_NAME = "es.snr.user";
    String SNR_PWD = "es.snr.password";
    String SNR_RETURN_INFO_LEVEL = "es.snr.returninfo.level";
    String SNR_RETURN_INFO_MODIFIER = "es.snr.returninfo.modifier";


    
    String  CVS_ENABLE                 = "es.compliancevalidation.enable";
    boolean CVS_ENABLE_DEFAULT         = true;
    String  CVS_ES_APP_ID              = "es.compliancevalidation.appid";
    String  CVS_ES_APP_ID_DEFAULT      = "ES";
    String  CVS_USER_ID                = "es.compliancevalidation.user";
    String  CVS_USER_ID_DEFAULT        = "ComplianceValidationService";
    String  CVS_USER_PASSWORD          = "es.compliancevalidation.password";
    String  CVS_USER_PASSWORD_DEFAULT  = "n3CoHPu%ooTW";
    String  CVS_THREAD_TIMEOUT  	   = "es.compliancevalidation.thread.timeout";

    String  CVS_SBS_LIFECYCLE          = "es.compliancevalidation.sbslifecycle";
    String  CVS_SBS_LIFECYCLE_DEFAULT  = "PRO";

    String  CVS_SBS_URL                = "es.compliancevalidation.url";
    String  CVS_SBS_URL_DEFAULT        = null;
	String CVS_INVALID_SN_ERROR_ID = "es.compliancevalidation.invalidSnId";
	String CVS_INVALID_SN_ERROR_ID_DEFAULT = "601";
	String CVS_INVALID_SN_ERROR_STR_DEFAULT = "Error: Product not eligible for service.  ";
	String CVS_INVALID_SN_ERROR_STR = "es.compliancevalidation.invalidSnText";
	

    
}
//EOF
